channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_varnishbundled_d7ca4bec4f
    grants:
      - 0
      - 2
      - 3
